### PR TITLE
Update k8s.io/cloud-provider-gcp/providers with the latest commit

### PR DESCRIPTION
**Pull request by panslava**
Commands ran:

- go get k8s.io/cloud-provider-gcp/providers@c2d05af3b14f885e2560139dd6fb4581ceb01733
- go mod tidy
- go mod vendor
- ./hack/update-codegen.sh

/assign @gauravkghildiyal @swetharepakula

### CODE REVIEW

**Comment by gauravkghildiyal** [comment]
It's possible the changes in `./hack` are not intentional? Can you double check?

**Comment by panslava** [comment]
my mistake... removed hack changes

**Comment by panslava** [comment]
Need to update composite types, working on that

**Comment by panslava** [comment]
should be done now, waiting for tests to pass

**Comment by gauravkghildiyal** [comment]
Thanks!

/lgtm

**Pull request merged**
