### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mgub**
The link to SSL certificate concepts was broken. I updated the link.

### CODE REVIEW

**Comment by mgub** [comment]
Here's a screenshot of the page pointed to by the broken link:

image

**Comment by rramkumar1** [comment]
@mgub Ping

**Comment by mgub** [comment]
@rramkumar1 Thanks for the ping. I checked out the branch locally with `git fetch origin pull/391/head:patch-1`, updated my credentials with `git commit --amend --reset-author` and tried to push the update with `git push --force` as outline on Step 4 in https://github.com/kubernetes/community/blob/master/CLA.md#the-contributor-license-agreement.

I get an error:
```
ERROR: Permission to kubernetes/ingress-gce.git denied to mgub.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

The original edit was made directly on GitHub. Any suggestions?

**Comment by rramkumar1** [comment]
@mgub Are you sure you were pushing to your remote origin and not upstream?

**Pull request merged**
