### PR TITLE
Bump k8s-cloud-provider to v1.20.0

### PR DESCRIPTION
**Pull request by spencerhance**
Re-vendoring required running go mod tidy as well; I split everything into separate commits to make it more clear.

### CODE REVIEW

**Comment by aojea** [comment]
/lgtm cancel

> I1111 08:41:43.268]     gen_test.go:1831: UrlMap should contain 19 fields. Got 18


is like some code needs to be regenerated?

**Comment by spencerhance** [comment]
Thanks @aojea!  Good thing I added that test :)  Re-ran the codegen script and it looks good now.

**Pull request merged**
