### PR TITLE
Update k8s-cloud-provider 

### PR DESCRIPTION
**Pull request by skmatti**
Part 1 of the Security Policy GA change

### CODE REVIEW

**Review by MrHohn — APPROVED** [review]
/lgtm
/approve

**Comment by MrHohn** [comment]
Actually, saw Bowei's comment on the child PR - https://github.com/kubernetes/ingress-gce/pull/1370#discussion_r580489962.

Feel free to un-hold after resolving.

**Comment by skmatti** [comment]
> Actually, saw Bowei's comment on the child PR - [#1370 (comment)](https://github.com/kubernetes/ingress-gce/pull/1370#discussion_r580489962).
> 
> Feel free to un-hold after resolving.

Thanks Zihong, added a tag now.

**Pull request merged**
