### PR TITLE
Switch to go modules

### PR DESCRIPTION
**Pull request by spencerhance**
- Updates vendor
- Pins all dependencies to their exact version

### CODE REVIEW

**Comment by rramkumar1** [comment]
@spencerhance My understanding was that for us to transition to modules, all our dependencies need to be on modules as well? Is that true?

**Comment by spencerhance** [comment]
@rramkumar1 That i'm not sure.  It seemed to me that it would handle non-module dependencies as before but I'm still investigating.

**Comment by rramkumar1** [comment]
@spencerhance Do you mind adding some docs under docs/dev/ for how to update dependencies?

**Comment by bowei** [comment]
can we try limiting this update to just moving to go modules? this change looks like it pulls a bunch of other stuff in, which makes it harder to review

**Comment by spencerhance** [comment]
@bowei I ran into some complications without running a `dep ensure -update` but I'll see if I can remove it.

**Comment by spencerhance** [comment]
@bowei I got rid of the composite changes and associated api version update so all changes should be localized to modules and vendor/ now

**Pull request merged**
