### PR TITLE
Deep copy service after getting from informer

### LINKED ISSUE #2135: L4 controller references cache objects
It seems that the controller build new objects that reference the existing object of the cache, I don't understand well enough to know if this is on. purpose, but it is risky since the cache is shared and I find very brittle if this new object works on a reference to the cache, maybe is safer to deepcopy the Service

https://github.com/kubernetes/ingress-gce/blob/0a822cc11ab9de1273f02fdeb1ad3768cd3cf8bd/pkg/l4lb/l4controller.go#L230-L238

https://github.com/kubernetes/ingress-gce/blob/0a822cc11ab9de1273f02fdeb1ad3768cd3cf8bd/pkg/l4lb/l4netlbcontroller.go#L581-L588

/kind bug
/assign @cezarygerard @panslava

### PR DESCRIPTION
**Pull request by panslava**
Fixes #2135 

/assign @aojea @cezarygerard

### CODE REVIEW

**Comment by aojea** [comment]
I don't know if this is the right fix

**Comment by cezarygerard** [comment]
lgtm

**Comment by aojea** [comment]
oh, when we were talking about deepcopy I thought that we were talking about the controller not this PR

I don't think this is a good solution, is very hidden in the code and you are going to propagate this change to all the users of this wrapper without them knowing

**Pull request merged**
