### PR TITLE
Rebase of #559 "Scaffolding for FrontendConfig"

### PR DESCRIPTION
**Pull request by spencerhance**
This PR is primarily a rebase of #559 which updates that PR to the latest state of ingress-gce.  

**Relevant issues:**  
https://github.com/kubernetes/ingress-gce/issues/515
https://github.com/kubernetes/ingress-gce/issues/731

### CODE REVIEW

**Comment by rramkumar1** [comment]
/lgtm
/hold

Looks good to me, one comment before merging: Can you merge the two commits "FrontendConfig type skeleton + generated code" & "Regen Frontend Config"

**Comment by spencerhance** [comment]
@rramkumar1 done.  Mind taking another look?

**Pull request merged**
