### PR TITLE
Add ListGlobalForwardingRules to the LoadBalancers interface.

### PR DESCRIPTION
**Pull request by G-Harmon**
I have an upcoming commit in the k8s-multicluster-ingress repo where I will use this.

cc @bowei @nicksardo @nikhiljindal

### CODE REVIEW

**Comment by nikhiljindal** [comment]
I see ListGlobalForwardingRules is implemented in GCECloud already: https://github.com/kubernetes/kubernetes/blob/6d32783453a6f624e9c0e2d818f58bdaa65199b3/pkg/cloudprovider/providers/gce/gce_forwardingrule.go#L73, so just adding it to the interface seems enough.

lgtm, but will wait for @bowei or @nicksardo to take a look and lgtm and merge.

**Comment by G-Harmon** [comment]
I updated the Fake so that it actually returns the current firewall rules. (I ended up using this logic in my commit for kubemci, which I haven't sent out yet.)

**Comment by nikhiljindal** [comment]
thx, still lgtm

**Pull request merged**
