### PR TITLE
Remove unnecessary interfaces in pkg/backends

### PR DESCRIPTION
**Pull request by TortillaZHawaii**
As per [Go Wiki](https://go.dev/wiki/CodeReviewComments#interfaces) interfaces should generally belong in the package that uses values of the interface type, not the package that implements these values. In this case there is no real added value of using interfaces instead of concrete types. We can safely remove them and get rid of boilerplate.

### CODE REVIEW

**Comment by mmamczur** [comment]
I does make the code follow go patterns a bit more, I'm adding Gaurav as well since this touches NEG pieces as well

/assign @gauravkghildiyal

**Comment by gauravkghildiyal** [comment]
Thanks @TortillaZHawaii !

/approve
/assign @mmamczur

**Pull request merged**
