### PR TITLE
[Cherry-pick #2186 -> 1.22] Include proxy-only subnet with purpose=REGIONAL_MANAGED_PROXY when generating firewall rules for Ingress

### PR DESCRIPTION
**Pull request by gauravkghildiyal**
Reverts kubernetes/ingress-gce#2204

/assign @swetharepakula
/hold

### CODE REVIEW

**Comment by gauravkghildiyal** [comment]
Good to go

/unhold

**Comment by swetharepakula** [comment]
do we have some tests to go with this change?

**Comment by gauravkghildiyal** [comment]
No we don't. This is tested in e2e

**Comment by swetharepakula** [comment]
Since tested in e2e, I am okay with merging 
/lgtm
/approve

**Pull request merged**
