### PR TITLE
Bump k8s-cloud-provider to v1.22.0

### PR DESCRIPTION
**Pull request by spencerhance**
This is needed to pull in https://github.com/GoogleCloudPlatform/k8s-cloud-provider/pull/79

### CODE REVIEW

**Comment by bowei** [comment]
I think it's possible to delete /vendor now?

**Comment by spencerhance** [comment]
```
Checking go vet: FAIL
# k8s.io/legacy-cloud-providers/gce
vendor/k8s.io/legacy-cloud-providers/gce/gce.go:542:18: cannot use &gceRateLimiter{…} (value of type *gceRateLimiter) as cloud.RateLimiter value in struct literal: *gceRateLimiter does not implement cloud.RateLimiter (missing method Observe)
```

Hmm it looks like https://github.com/GoogleCloudPlatform/k8s-cloud-provider/pull/77 is conflicting with `k8s.io/legacy-cloud-providers/gce/gce.go`

https://github.com/kubernetes/legacy-cloud-providers/blob/master/gce/support.go#L45

**Comment by spencerhance** [comment]
https://github.com/kubernetes/kubernetes/pull/116448 for the fix

**Comment by gauravkghildiyal** [comment]
Thanks a lot lot Spencer!

**Comment by spencerhance** [comment]
Whoops, missed a `vendor/` file, updated now.

**Pull request merged**
