### PR TITLE
Add API changes for backendconfig custom response header feature

### PR DESCRIPTION
**Pull request by songrx1997**
/assign @swetharepakula

### CODE REVIEW

**Comment by swetharepakula** [comment]
Thanks for the change Ruixian! 
/lgtm

@spencerhance any other feedback before this can be merged?

**Comment by spencerhance** [comment]
looks good to me!  

Side note, we probably want to send a PR first to update the generated code.  It looks like some unrelated stuff was out of date.

**Comment by songrx1997** [comment]
> looks good to me!
> 
> Side note, we probably want to send a PR first to update the generated code. It looks like some unrelated stuff was out of date.

Thanks @spencerhance , will do this.

**Pull request closed without merging**
