### PR TITLE
Scaffolding for FrontendConfig 

### PR DESCRIPTION
**Pull request by rramkumar1**
This PR adds the scaffolding needed to implement features for a FrontendConfig CRD. 

A follow up PR will be added to include some documentation for contributors + possibly an example implementation as well.

Relevant Issue: #515

### CODE REVIEW

**Comment by binoculars** [comment]
Any updates here? Would really like to be able to set an SSL Policy from an annotation.

**Comment by bowei** [comment]
We have it next on our backlog, this should be moving shortly...

**Comment by rramkumar1** [comment]
Closing in favor of #753

**Pull request closed without merging**
