### PR TITLE
Refactor ServerErrror helper functions

### PR DESCRIPTION
**Pull request by swetharepakula**
* Remove infinite for loop since errors.As finds the relevant error
 * Add tests to validate the functions work for multi-wrapped errors

/assign @bowei 
/cc @gauravkghildiyal

### CODE REVIEW

**Comment by gauravkghildiyal** [comment]
Thanks for making this change.

This LGTM.

**Comment by bowei** [comment]
Did we test the previous behavior to see what happens in the original case?

**Comment by swetharepakula** [comment]
Yes, we did, anytime there is a "%w:%w" error, the original functions result in an infinite loop

**Comment by bowei** [comment]
How does the controller work then? Wouldn't all of the syncs get stuck?

**Pull request merged**
