### PR TITLE
Bump go version to 1.19

### PR DESCRIPTION
**Pull request by sugangli**

### CODE REVIEW

**Comment by aojea** [comment]
this only bumps the go.mod, if you want to build with go 1.19 you have to switch the build image

https://github.com/kubernetes/ingress-gce/blob/f3c56e747e4098fc553a32f23ca2b9419bc8cde2/Makefile#L45

**Comment by sugangli** [comment]
> this only bumps the go.mod, if you want to build with go 1.19 you have to switch the build image
> 
> https://github.com/kubernetes/ingress-gce/blob/f3c56e747e4098fc553a32f23ca2b9419bc8cde2/Makefile#L45

Oh right. Forgot about that. Updated.

**Pull request closed without merging**
