### PR TITLE
clean up HTTP(S) resources when changing protocols

### PR DESCRIPTION
**Pull request by agau4779**

### CODE REVIEW

**Comment by rramkumar1** [comment]
/lgtm
/hold

Will merge this once there is an e2e test.

**Comment by bowei** [comment]
/assign @spencerhance 

Looks like this just needs to get fixed, assigning to you to keep in the backlog

**Comment by spencerhance** [comment]
ack

**Comment by bowei** [comment]
This is being fixed as part of other work that will be published soon.

**Pull request closed without merging**
