### PR TITLE
Bugfix: Use Static IP to create forwarding rule when available

### PR DESCRIPTION
**Pull request by skmatti**
Fixes https://github.com/kubernetes/ingress-gce/issues/993

### CODE REVIEW

**Comment by bowei** [comment]
does this need cherry pick back to previous release?

**Comment by skmatti** [comment]
> does this need cherry pick back to previous release?
Yes, this needs to be be cherry picked.

However, this is not common in old versions or may be not considered a bug?.
The occurrence of following events associated an ingress leads to the bug,
1. Enable both http and https
3. Delete http forwarding rule manually from GCP
4. Make changes to ingress so a sync is triggered

At this point, Both http and https have a VIP each created in GCP. And, only VIP associated with http is shown in ingress status.

**Pull request merged**
