### PR TITLE
[1.20] Update go version and some dependendies

### PR DESCRIPTION
**Pull request by songrx1997**
Upgrade go version to 1.20
Upgrade github.com/prometheus/client_golang to v1.11.1
Upgrade k8s.io/client-go to v0.27.0

/assign @swetharepakula

### CODE REVIEW

**Comment by swetharepakula** [comment]
/ok-to-test

Same comment as #2272. Can you break this into 3 commits to make it easier to review. Thanks!

**Comment by songrx1997** [comment]
The lint check in test failed. We are going to bypass this check to update the version. 

Run several e2e tests locally as sanity check:

Screenshot 2023-09-28 at 11 53 22 PM

Also all other checks and tests passed in  `pull-ingress-gce-test`.

@bowei Could you review this?

**Comment by swetharepakula** [comment]
/lgtm
/approve

@bowei, can you review and merge. We should bypass the golinter in this case since this is a cherry-pick to update just the go modules with no functionality change and the golinter is passing on master and our current release versions.

**Comment by aojea** [comment]
the errors look legit to me, why can't we fix the errors?

**Comment by aojea** [comment]
/hold

those errors does not seem right

**Comment by aojea** [comment]
/hold cancel

Talked with @songrx1997 offline, verified that are only linter problem, the job logs are noisy and I was worried we may merge something that can cause problems later

**Comment by bowei** [comment]
There seems to be some issues with the linter, merging.

**Pull request merged**
