### PR TITLE
 Add beta backend service support to composite type

### PR DESCRIPTION
**Pull request by MrHohn**
/assign @rramkumar1

### CODE REVIEW

**Comment by rramkumar1** [comment]
@MrHohn Can you link the corresponding PR in k/k for the vendored code?

**Comment by MrHohn** [comment]
Sure, that is kubernetes/kubernetes#64793.

**Comment by nicksardo** [comment]
Is there a PR for updating the generated client?

**Comment by rramkumar1** [comment]
It should be linked in a comment above

**Comment by nicksardo** [comment]
Sorry, blind.

**Pull request merged**
