### PR TITLE
[Cherry-pick #2708 -> 1.31] Fix port range to port comparison for forwarding rules

### PR DESCRIPTION
**Pull request by TheBeeZee**
This fixes a bug when an existing forwarding rule lists a distinct a set of ports. If a new port is added to a load balancer that falls within the same range of ports, the forwarding rule will not be updated because we would compare the old and new list of ports as a port range.

For example, with oldPorts = {1, 5, 10} and newPorts = {1, 5, 6, 10}, both old and new ports are converted to port range 1-10 and no change is made to the forwarding rule.

With this change we only convert new ports to a port range if the existing ports are also a port range.

### CODE REVIEW

**Comment by mmamczur** [comment]
can we make sure the name of the PR and comming message follow the pattern `[Cherry-pick #2708 -> 1.31]`

Other than that lgtm

but I'm not sure how we plan to release, @swetharepakula will we do any more releases from ingress-gce release-1.31 branch?

**Comment by FelipeYepez** [comment]
This fixes an issue present in release-1.31 so we need to cherry pick this

**Comment by mmamczur** [comment]
> This fixes an issue present in release-1.31 so we need to cherry pick this

but if we cut a new branch 1.32 and use that then 1.31 may not be needed anymore. ingress-gce 1.32 will be used in gke 1.31.

**Comment by FelipeYepez** [comment]
I see, thanks.

**Comment by TheBeeZee** [comment]
> can we make sure the name of the PR and comming message follow the pattern `[Cherry-pick #2708 -> 1.31]`
> 
> Other than that lgtm
> 
> but I'm not sure how we plan to release, @swetharepakula will we do any more releases from ingress-gce release-1.31 branch?

I have updated the description. I'm ok with either cherrypicking into 1.31 or releasing as 1.32, whichever is the proper solution.

**Pull request merged**
