### PR TITLE
Cherry-pick  #1209 [Expose custom health check ports in the firewall] into release-1-9

### PR DESCRIPTION
**Pull request by spencerhance**
Also includes the commit from #1084 in order to cherry-pick in the e2e tests as well

### CODE REVIEW

**Comment by rramkumar1** [comment]
@spencerhance Let's keep the cherry pick clean. Can you send a separate PR for the test.

**Comment by spencerhance** [comment]
@rramkumar1 Sure thing.  Should I just include 007bf05 and not include 54885c3 from the original PR?

**Comment by rramkumar1** [comment]
The cherrypick should only contain the same commits from the corresponding PR which was merged to HEAD.

**Comment by spencerhance** [comment]
Hmm okay.  I don't see a reasonable way to cherry-pick both commits from #1209 without including bowei's e2e stuff.  I can just cherry-pick 007bf05 and not include the other commit in this PR.

**Pull request merged**
