### PR TITLE
Migrate gce-ingress to configmaps-leases leaderelection lock

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref https://github.com/kubernetes/ingress-gce/issues/1590

/assign @bowei @freehan

### CODE REVIEW

**Review by freehan — APPROVED** [review]
/lgtm
/approve

**Comment by freehan** [comment]
Does this require graceful migration between the 2 mechanism? Or they are okay to migrate directly?

**Comment by wojtek-t** [comment]
> Does this require graceful migration between the 2 mechanism? Or they are okay to migrate directly?

This one is graceful migration (intermediate step) towards eventual step (lease-based election).
So this PR can just be deployed as is without any additional action.

@freehan ^^

**Comment by acumino** [comment]
Why do we need this https://github.com/kubernetes/ingress-gce/blob/b589a5813e6b4fe9f35d7674df43c4825380bcb0/pkg/flags/flags.go#L50 if any way we are setting the resource lock explicitly here https://github.com/kubernetes/ingress-gce/blob/b589a5813e6b4fe9f35d7674df43c4825380bcb0/cmd/glbc/main.go#L228-L236

**Pull request merged**
