### PR TITLE
Add HealthCheckConfig to v1beta1 BackendConfig CRD

### PR DESCRIPTION
**Pull request by AnishShah**

### CODE REVIEW

**Comment by omatsko** [comment]
If this is going to be included with the next release, could someone please tell when is it planned?

**Comment by rramkumar1** [comment]
@omatsko We are planning to include this as part of our 1.10 release. We are about to release 1.9 so 1.10 will hopefully drop in a couple weeks after that. Will keep this thread updated.

**Comment by bryanhuntesl** [comment]
> @omatsko We are planning to include this as part of our 1.10 release. We are about to release 1.9 so 1.10 will hopefully drop in a couple weeks after that. Will keep this thread updated.

Any news - id I understand correctly, this prevents exposing grafana because / returns 302 - and the healthcheck configured for the service is ignored by the ingress ?

**Comment by tmc** [comment]
@rramkumar1  It seems missed here to not allow Host header configuration, thoughts?

**Comment by mad-it** [comment]
Any updates on the release schedule for this?

**Comment by johndoe123441** [comment]
Looking for an update on this item

**Comment by Gatsby-Lee** [comment]
This merged seems available on beta. I am on 1.17.6-gke.11.

I don't need change in Ingress.

```yaml
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: config-default
  namespace: apimars-prod
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 3
    requestPath: /healthz
```

```
apiVersion: v1
kind: Service
metadata:
  name: test-healthz
  namespace: apimars-prod
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    beta.cloud.google.com/backend-config: '{"default": "config-default"}'
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: test-healthz
  type: NodePort
```

**Comment by Gatsby-Lee** [comment]
I was wrong. I don't think setting healthcheck through Backendconfig works.
Ingress can use custom healthcheck only if Service exists before Ingress knows about the Service.

And, even if custom healthcheck works by bringing up Ingress after Service,
the custom healthcheck won't work if new Pod is deployed.

This is what @nicksardo explained before in different msg thread.

BTW, ingress doesn't have to be removed to use custom healthcheck.
if Service info is removed from Ingress and added back again, then Ingress uses custom healthcheck again.
(But, we can't do this on prod) lol

**Pull request merged**
