### PR TITLE
Small fix for README

### PR DESCRIPTION
**Pull request by Megalepozy**

### CODE REVIEW

**Comment by Megalepozy** [comment]
/assign @thockin 

Hey that's what the bot told me ;)

**Comment by Megalepozy** [comment]
How about now?

**Comment by rramkumar1** [comment]
@Megalepozy It doesn't seem to be working.

**Comment by Megalepozy** [comment]
@rramkumar1 yeah just updated my last comment about that, if u can just take the change and apply it, its really small :)

**Comment by rramkumar1** [comment]
@Megalepozy Sure, I will close this PR then.

/close

**Pull request closed without merging**
