### PR TITLE
Remove Services.Get() from syncNegStatusAnnotation()

### PR DESCRIPTION
**Pull request by gauravkghildiyal**
/assign @swetharepakula

### CODE REVIEW

**Comment by mmamczur** [comment]
we tried a very similar thing along with adding more goroutines for the controller itself. It seemed to definitely help in manual testing.

I'm not sure why it was getting the service from a client before though. Can patch fail if we give it an outdated version?

**Comment by gauravkghildiyal** [comment]
@swetharepakula gave some historical context for this: Fetching the service from the api-server was needed when `patch` didn't exist and we had to work with `update`s APIs. When we replaced the APIs to use `patch` instead of `update`, replacing this specific Get call to the api-server most likely got missed.

There are existing places in our code ([example1](https://github.com/gauravkghildiyal/ingress-gce/blob/fa6f5a6df062f1ba7c419fc068db4bb2fbbb276b/pkg/neg/syncers/transaction.go#L665), [example2](https://github.com/gauravkghildiyal/ingress-gce/blob/fa6f5a6df062f1ba7c419fc068db4bb2fbbb276b/pkg/neg/syncers/transaction.go#L693)) where we do fetch from the informer and then perform the update and I feel this should be fine too.

There's atleast one other place I know where we could also fetch from the informer. That, along with increasing the number of workers and a few other optimizations is something that I'm working on and will soon send them in separate PRs.

**Comment by mmamczur** [comment]
let's have this merged then (I can't review nor lgtm yet)
/lgtm

**Review by swetharepakula — COMMENTED** [review]
/lgtm
/approve

**Comment by gauravkghildiyal** [comment]
> New changes are detected. LGTM label has been removed.

FYI: Just rebased -- no new changes

**Comment by aojea** [comment]
you have to remove some unused code now

> pkg/neg/controller.go:20:2: imported and not used: "context"
> pkg/neg/controller.go:27:2: imported and not used: "k8s.io/apimachinery/pkg/apis/meta/v1" as metav1

**Pull request merged**
