### PR TITLE
Rename projectinformer to filteredinformer

### PR DESCRIPTION
**Pull request by panslava**
As we added ClusterSlice now, let's rename projectinformer to filteredinformer which will filter based on cluster slice name label

/assign @gauravkghildiyal

### CODE REVIEW

**Comment by panslava** [comment]
tests failing with

 'ERROR: failed to acquire GCP project. boskos response was: Acquire failed: no available resource gce-project, try again later.'

**Comment by gauravkghildiyal** [comment]
I'm guessing that unfortunately, this needs another round of renaming?

**Comment by gauravkghildiyal** [comment]
(This is also LGTM, pending renaming)

**Comment by panslava** [comment]
renamed to provider config, ready for re-review @gauravkghildiyal

**Comment by gauravkghildiyal** [comment]
Thanks!

/lgtm

**Pull request merged**
