### PR TITLE
Update healthcheck docs regarding containerPort

### PR DESCRIPTION
**Pull request by sonu27**
Fixes issue #241

### CODE REVIEW

**Comment by sonu27** [comment]
@nicksardo Let me know if this is clear enough :)

**Comment by nicksardo** [comment]
Thanks for creating this PR @sonu27.  However, it's not matching the servicePort, it's matching the service's targetPort.  It's also complicated because names can be used...

```
The pod's `containerPort` field must be defined.
The service's `targetPort` field must point to the pod port's `containerPort` value or `name`. Note that the `targetPort` defaults to the `port` value if not defined.
```
Feel free to re-phrase any of that. 

This might make more sense
Ingress `servicePort` ▶ Service port.`port` || port.`name`
Service `targetPort` ▶ Pod port.`containerPort` || port.`name`
ReadinessProbe `port` ▶ Pod port.`containerPort` ||  port.`name`

**Comment by sonu27** [comment]
Your wording is good.

I was thinking of added the bottom bit, as it explains it cleanly but possibly too much :)

**Pull request merged**
