### PR TITLE
Remove running tests with verbose mode

### PR DESCRIPTION
**Pull request by panslava**
We have too many logs in all tests

/assign @aojea @swetharepakula @gauravkghildiyal

### CODE REVIEW

**Comment by aojea** [comment]
that is on purpose, otherwise how do you debug the failures?

**Comment by panslava** [comment]
@aojea how it works, at least for me, without -v it will print logs for the tests that failed, but not for all of the tests

image

**Comment by aojea** [comment]
your tests show (cached), you need to use `-count 1` to not run the cached test

**Comment by aojea** [comment]
indeed `-v` logs everything
```
        -v
            Verbose output: log all tests as they are run. Also print all
            text from Log and Logf calls even if the test succeeds.
```
so I think is a matter of taste then https://grep.app/search?q=go%20test%20-v&filter[lang][0]=Go, 

I like to run verbose on CI but I can't see any other reason to not do it, up to you then

**Comment by aojea** [comment]
/lgtm

it is ok

**Pull request merged**
